name: GardenCore
version: '${project.version}'
main: com.pallux.gardencore.GardenCore
api-version: '1.21'
description: Core plugin for Garden Simulator Tycoon Server by Pallux
authors: [ Pallux ]
softdepend: [ PlaceholderAPI, WorldEdit, FastAsyncWorldEdit ]

permissions:
  gc.admin:
    description: Access to admin commands
    default: op
  gc.player:
    description: Access to player commands
    default: true
  gc.bypass.nodrop:
    description: Bypass the no-drop feature
    default: op
  gc.bypass.nofalldamage:
    description: Bypass the no-fall-damage feature
    default: op
  gc.bypass.nohunger:
    description: Bypass the no-hunger feature
    default: op
  gc.bypass.noblockdrops:
    description: Bypass the no-block-drops feature
    default: op
  gc.bypass.instantreplant:
    description: Bypass the instant-replant feature
    default: op
  gc.bypass.noncropsbreak:
    description: Bypass the no-non-crop-break feature (allows breaking any block)
    default: op

commands:
  upgrade:
    description: Open the upgrade GUI or upgrade a specific perk
    usage: /upgrade [fiber_amount|material_amount|material_chance]
    permission: gc.player
  gca:
    description: GardenCore admin commands
    usage: /gca <subcommand>
    permission: gc.admin
  research:
    description: Open the Research GUI
    usage: /research
    permission: gc.player
  garden:
    description: Open the Garden main menu
    usage: /garden
    permission: gc.player
  islands:
    description: Open the Island travel menu
    usage: /islands
    permission: gc.player
  elder:
    description: Open the Elder Council perk menu
    usage: /elder
    permission: gc.player
  pets:
    description: Open the Pets menu
    usage: /pets
    permission: gc.player